### ISSUE TITLE
check for negative on take (< and >) operators

### ISSUE THREAD

**Issue by nick-paul** [nick-paul/element-lang#10]
element> 10R (-4)<
java.lang.IllegalArgumentException: Illegal Capacity: -4
	at java.util.ArrayList.<init>(ArrayList.java:156)
	at element.entities.operations.OP_LessThan.execute(Ops.java:661)
	at element.entities.Block.eval(Block.java:123)

**Comment by nick-paul** [comment]
Just change .toInt() to .toIndex() for both operators
