### ISSUE TITLE
error reading stdin

### ISSUE THREAD

**Issue by nick-paul** [nick-paul/element-lang#11]
echo "47 3 +" | element -i
All tests passed! (3 tests ran)
      _                           _     |  A stack based progrgramming language
  ___| | ___ _ __ ___   ___ _ __ | |_   |  for code golf and other puzzles
 / _ \ |/ _ \ '_ ` _ \ / _ \ '_ \| __|  |  
|  __/ |  __/ | | | | |  __/ | | | |_   |  Version: Beta 0.0.9 (Nov 2016)
 \___|_|\___|_| |_| |_|\___|_| |_|\__|  |  Nicholas Paul

element> 50
element> Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
	at element.InteractiveElement.main(InteractiveElement.java:251)
	at ui.ElementIDE.main(ElementIDE.java:406)
nick@nick-laptop:~$

**Comment by nick-paul** [comment]
A fix to this issue should allow piping to work smoothly
