### ISSUE TITLE
SortUsing integer cast

### ISSUE THREAD

**Issue by nick-paul** [nick-paul/element-lang#2]
element> "testss" sc
java.lang.ClassCastException: java.lang.Integer cannot be cast to element.entities.number.Numeric
	at element.ElemTypes.toNumeric(ElemTypes.java:169)
	at element.entities.operations.OP_Dot_SortUsing.execute(DotOps.java:235)
	at element.entities.Block.eval(Block.java:123)
	at element.Element.run(Element.java:97)
	at element.Element.run(Element.java:130)

**Comment by nick-paul** [comment]
Fixed along with issue #6
